### ISSUE TITLE
Window not drawing until ConfigureNotify event received

### ISSUE THREAD

**Issue by aolo2** [nakst/gf#12]
On lauching gf, the window is created but nothing is drawn. It only after grabbing the window, dragging, and *releasing* it, the contents start to draw. The problem persists both with- and without enabling the compositor.

I'm using X.org.

Demonstration: https://youtu.be/1XJuA_phkeo

**Comment by aolo2** [comment]
Hmm, it seems this only happens if another window is already open. If gf is the only window, is draws instantly. Some x11 event related probably?

**Comment by aolo2** [comment]
It's almost certanly `ConfigureNotify`.

**Comment by nakst** [comment]
What window manager are you using?

**Comment by aolo2** [comment]
I'm on Openbox 3.6.1

**Comment by nakst** [comment]
Could you try adding

    XResizeWindow(ui.display, window->window, width + 1, height + 1);
    	
after the call to `XMapRaised` and see if makes a difference?

**Comment by aolo2** [comment]
This got fixed, by the way. I have no idea where or how, though..
