### ISSUE TITLE
[feature request] Horizontal scrollbars

### ISSUE THREAD

**Issue by flysand7** [nakst/gf#131]
I'm debugging a project that has very long lines that don't fit on my screen even if I made gf window as big as my screen. There's no option to enable wrapping of lines or scroll the window, which is a lot of inconvenience.

**Comment by s4my** [comment]
I second this. This is a basic thing any scroll area should have (the command output comes to mind as well). But am not so sure if luigi (UICode i think to be precise) has this ability right now ?

**Comment by nakst** [comment]
Commit 2245028 adds horizontal scroll bar support to `UICode` with the flag `UI_CODE_H_SCROLL`.
Although I'm undecided as to whether this should actually be used in the source code window or the console.

**Comment by s4my** [comment]
> Commit [2245028](https://github.com/nakst/gf/commit/22450287b3b4cc16d32a5937d04ee1245acdae6e) adds horizontal scroll bar support to `UICode` with the flag `UI_CODE_H_SCROLL`. Although I'm undecided as to whether this should actually be used in the source code window or the console.

Nice, my suggestion is to remove if condition in https://github.com/nakst/gf/blob/master/luigi2.h#L2845 
```diff
-	if (flags & UI_CODE_H_SCROLL) code->hScroll = UIScrollBarCreate(&code->e, UI_SCROLL_BAR_HORIZONTAL);
+ 	code->hScroll = UIScrollBarCreate(&code->e, UI_SCROLL_BAR_HORIZONTAL);
```
This way all the UICode elements will dynamically show the horizontal scrollbar if the window size is too small to display all of it's contents 👍🏻

**Comment by s4my** [comment]
i also noticed that when the horizontal scroll bar is no longer needed, we need to reclaim the space where it was.

**Comment by s4my** [comment]
i just noticed another visual enhancement, at this point i might as well just make a pull request.
