### ISSUE TITLE
Menu button crashes

### ISSUE THREAD

**Issue by phmongeau** [nakst/gf#14]
Hey nakst, I'm getting a crash on the latest version when I click the Menu button.
```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  1 (X_CreateWindow)
  Value in failed request:  0x0
  Serial number of failed request:  237
  Current serial number in output stream:  242
```

It seems to be caused by  [this change](https://github.com/nakst/gf/commit/f7d932f75784922c33ed158e86dd10501fd5a8d3#diff-e7d99097f6de6f19966fa409b94e1994c90ef0ea4d8543dbbe636f63a3b20d13R3951)

I'm not sure what's the intended behavior here, but the docs says width and height should be nonzero:
https://www.x.org/releases/current/doc/libX11/libX11/libX11.html#XCreateWindow

**Comment by nakst** [comment]
Should be fixed in 539df72.

**Comment by phmongeau** [comment]
Thanks for the quick fix!
Now I'm getting a segfault on [XStoreName](https://github.com/nakst/gf/blob/master/luigi.h#L3956) when cTitle is null.
This wasn't an issue before so I'm a bit confused, might be caused by an x11 update

**Comment by nakst** [comment]
As of 8533174 `XStoreName` is only called if `cTitle` is non-null.

**Comment by phmongeau** [comment]
Seems good, thanks!
