### ISSUE TITLE
Bitmap live update

### ISSUE THREAD

**Issue by aolo2** [nakst/gf#16]
This one is quite big, because setting the parameters every time is quite tedious. To my understanding, the bitmap data is sent over gdb's MI, which means it's really slow. So I propose a switch (a checkbox) on a bitmap preview, which allows you to toggle live preview on-off. This checkbox can then be off by default.

That's one of those things where having your own debugger instead of gdb would make things so much simpler...

**Comment by nakst** [comment]
By "live update" do you mean while the target application is running, or only when stepping through code?

For now, I've added a button to manually refresh the bitmap viewer, and I've also improved the speed of extracting the bitmaps from the GDB.

**Comment by aolo2** [comment]
I mean at the same time the watched variables are updated (i.e. every time a program stops because of breakpoint hit, step finished etc).

**Comment by nakst** [comment]
Added in 9a5e5c7, but I haven't tested it much.

**Comment by aolo2** [comment]
A quick test worked well for me. It's pretty fast also!
