### ISSUE TITLE
Watch window strategy?

### ISSUE THREAD

**Issue by aolo2** [nakst/gf#17]
Good day Mr. Nakst, the progress so far has been amazing, and `gf` is already a pleasure to use!

Today I want to talk the watch window. I've compiled v1 of `gf`, and it seems you went the same way as `DDD` as far as data display goes. Now, such approach is definitely very useful for visualizing things like linked lists, trees etc, but I think a conventional 3-column view is better suited for more common use-cases. The traditional view can also intuitively be navigated with a keyboard. And, of course, every GUI debugger ever has a watch window, so the UX is well established and there is practically no learning curve for switching to `gf`.

However, I do feel that the "advanced" view is really helpful in some scenarios. In fact, viewing bitmaps is already a good example: seeing a few bitmaps at once, as well as being able to zoom and pan doesn't feel like something that could be  done well in a traditional watch window.

So I propose a split: "watch" tab gets a good-ol' 3-column view, while the "data" tab is where users go to perform advanced data visualization.

What are your (or anyone else's who is reading this) thoughts on this?

**Comment by nakst** [comment]
Basic watch window added in 2a108f7.

**Comment by aolo2** [comment]
I've used the new watch window for some time now, and I've nothing bad to say about it. The only thing would be editing the expression (it's not fun completely re-typing `*graphics_state->stack@graphics_state->stack_head` after mistyping one letter). Other than that, it'd be cool to be able to place the watch tab somewhere else (as it is now, it's quite small, and can't be made taller without making the whole bottom panel tall, which takes space from the source code), but that's more regarding UI than the watch window in particular.

But don't get me wrong, it's 100% usable, and infinitely better than anything tui-based! I guess, what I'm trying to say is this issue can be closed. Thank you for doing this!

**Comment by nakst** [comment]
You can now modify existing watch expressions by pressing backspace with the expression selected. Added in 8935299.

**Comment by nakst** [comment]
> Other than that, it'd be cool to be able to place the watch tab somewhere else (as it is now, it's quite small, and can't be made taller without making the whole bottom panel tall, which takes space from the source code), but that's more regarding UI than the watch window in particular.

I agree completely. I would like to improve the layout of the interface; some things take up far more space than necessary (i.e. the breakpoints window). 
Create a new issue if you have any specific ideas how things could be improved!
