### ISSUE TITLE
Show hex value instead of decimal in Locals tab

### ISSUE THREAD

**Issue by barbozafernando** [nakst/gf#171]
Instead of showing decimal values (71, 116) show hex values (47, 74)

![image](https://github.com/nakst/gf/assets/45888984/54326e23-0a42-4bf9-a26a-5481b886278c)

**Comment by nakst** [comment]
Click on the row containing the value you want in hex, then type `/x` on your keyboard.

**Comment by barbozafernando** [comment]
I think that it could be a config on the .ini file. It'll be nice.
