### ISSUE TITLE
Feature request: Allow typing/executing gdb commands via the (gdb) prompt/window

### ISSUE THREAD

**Issue by debashisde** [nakst/gf#179]
Hi,

This is a feature request:
Is it possible to allow typing/executing gdb commands via the (gdb) prompt/window?
That would make a nice enhancement for the console gdb users like me.

Thanks,
Debashis

**Comment by greg7mdp** [comment]
You can type gdb commands in that input box at the bottom left, right next to `Menu`.

**Comment by debashisde** [comment]
Nice.
Sorry for bothering you and thanks for the pointer.
I was actually trying to type on the (gdb) prompt.

I have one more question/suggestion: is it possible to specify the initial
window size (geometry) or the state (full-screen)?
I want it to start up in full-screen mode.

I am actually using it with rr and the [gdb] options "path" and "arguments"
fit nicely in this case.

Thanks again for the nice tool. I like it very much.

Regards,
Debashis

**Comment by greg7mdp** [comment]
I'm not the author, just a user.

I also wanted to be able to set the window size, so I added the following in my (modified) version of `gf.c`:

![image](https://github.com/user-attachments/assets/8ecf044c-3d83-473e-acf5-a7e372c90d69)

which allows for the window_size stuff in the `ui` section of gf2_config.ini:

```
[ui]
scale=1
font_path=/home/greg/fonts/FiraCode-Regular.ttf
font_size=12
window_width=3000
window_height=1700
```

**Comment by debashisde** [comment]
Thanks for the suggestion.
Will try it out.

**Comment by debashisde** [comment]
I confirm that your suggestion is working perfectly.
Thanks again.

**Comment by greg7mdp** [comment]
Cool, maybe close the issue then, have fun with gf2!

**Comment by debashisde** [comment]
Thanks.
