### ISSUE TITLE
Switching between source files (tabs)

### ISSUE THREAD

**Issue by aolo2** [nakst/gf#18]
As it is now, `gf` only shows the current source file. This leaves the only one way of setting breakpoints in other files: using the gdb console. It's not that bad for a personal project with a dozen files, but becomes increasingly hard to do in larger projects, because you have to remember the filename. Tabs, as I understand, are already implemented in the UI framework (except for scrolling maybe).

You could use `info sources` to get the source paths.

**Comment by nakst** [comment]
When I want to set a breakpoint at a specific location I use the F2 shortcut (sync file and line with text editor). 

(This is, in my opinion, much preferable to having to manage your files and tabs in both your text editor and debugger. When I'm on Windows this is my main friction point when working with Visual Studio.)

The only problem with this feature is that it currently only supports GVIM! If you have a specific editor in mind that you want me to add, I'll have a look into it.

**Comment by nakst** [comment]
I added a basic directory browser in 0196a75, for when text editor integration is not possible; however, for the reasons stated above, I will not be adding tabs to the source viewer.
