### ISSUE TITLE
Run configurations

### ISSUE THREAD

**Issue by aolo2** [nakst/gf#19]
My typical launch of `gf` goes like this:
1. Open `gf`
2. Type `file /code/my/working/dir/exe-file` in the gdb console
3. Type `start /code/my/working/dir/input-file` in the gdb console

For one project with one never-changing argument this can easily be automated with a launch script along the lines:
```gf2 /code/my/working/dir/exe-file --args  /code/my/working/dir/input-file```

However, after introducing multple executables with multiple argument combinations, the scripts are not going to help. 
Traditionally, you would have some kind of a "run configuration", which specifies the path to the executable, the working directory, program arguments, and the environment variables. These configurations can be then selected from a list. On lauch, either no configuration is selected, or the last one is auto-loaded.

Having something along these lines would be great.

**Comment by nakst** [comment]
Added in ee8f43b, see https://github.com/nakst/gf/#preset-commands for documentation.

**Comment by aolo2** [comment]
That's a funny way of solving the problem, but it totally works, thanks!
