### ISSUE TITLE
Ability to text-edit the color values

### ISSUE THREAD

**Issue by aolo2** [nakst/gf#24]
I'm currently messing with the theme editor, trying to duplicate my code editor color scheme. However, the color values are editable only with the color wheel, which does not allow me to reproduce the colors exactly. The `.gf_theme.dat` file is also binary, so I can't edit it that way. Would be nice if the color values were editable as a regular text field, so that I could just copy-paste the color values.

**Comment by nakst** [comment]
I've decided to remove the theme editor. It was badly ported from the example application for Luigi, and has never been very useful. Instead the theme is controlled from the config file; the old theme will be converted automatically. Sample themes have been moved to https://github.com/nakst/gf/wiki/Themes.
