### ISSUE TITLE
Format specifiers for the watch window

### ISSUE THREAD

**Issue by aolo2** [nakst/gf#27]
First of all, the watch window is working great, thank you!

Now, currently if I need to view the value in hex or in binary, I'm forced to use the Console window. It's alright for one-off prints, but if I want to watch the value, it quickly becomes unusable (you probably know what I mean: try having more than a few `display`-ed structs in gdb). This calls for passing format specifiers (/x, /t) to gdb somehow. As far as I know, this is usually done using the `,` operator: `my_val, x` is translated to `p/x my_val`. But this includes parsing the expression, so be vary! Maybe just a context menu on the values (show in hex, show in binary)?

**Comment by nakst** [comment]
Added. Press `/` with a watch expression selected to change the format character.
