### ISSUE TITLE
Step out of block doesn't work

### ISSUE THREAD

**Issue by aolo2** [nakst/gf#35]
What the title says.

**Comment by nakst** [comment]
Could you give an example where it does not work? (It is working for me.)

**Comment by aolo2** [comment]
It does appear to work on a super-simple example, but not on any of my actual code. Here's a snippet where I can't step out of block on *any* of the lines (`until` command doesn't get passed to gdb at all):

```
while (*p != 0) {
    if (dest_files) {
        dest_files[nfiles].filename = (char *) p;
    }
    
    while (*p != 0) {
        ++p;
    }

    ++p;
    
    // ...
    
    if (dest_files) {
        if (dir_index) {
            dest_files[nfiles].dir = dest_directories[dir_index - 1];
        } else {
            dest_files[nfiles].dir = ".";
        }
    }

    p += offset;
}
```

**Comment by nakst** [comment]
Does commit 99a358b work?

**Comment by aolo2** [comment]
It does, thanks!
