### ISSUE TITLE
Problems with the path to the source files

### ISSUE THREAD

**Issue by MrOneTwo** [nakst/gf#38]
I'm running the gf2 with arm-none-eabi-gdb-py and gf2 has problems establishing proper paths to the source files.

So the project dir is `/home/mc/gits/paw-usb/`, the source dir is `/home/mc/gits/paw-usb/src` and all the compilation happens through the Makefile that lives in `/home/mc/gits/paw-usb/src`.

I've changed `DisplaySetPosition`, this line: https://github.com/nakst/gf/blob/9996fedd567b23b0719abf41474403ee2c8ed0d9/windows.cpp#L65
I've changed the `originalFile` to `currentFileFull`, just for debug purposes, and it prints `/home/mc/gits/paw-usb/main.c` path. It's missing the `src/` part. The full message is:

```
The file 'main.c' (from '/home/mc/gits/paw-usb/main.c') could not be loaded.
```

**Comment by MrOneTwo** [comment]
I'm also getting `Python Exception <type 'exceptions.NameError'> Installation error: gdb.execute_unwinders function is missing:` so maybe my setup is a bit broken.

**Comment by nakst** [comment]
> I'm running the gf2 with arm-none-eabi-gdb-py and gf2 has problems establishing proper paths to the source files.

After your process has started, try clicking `Menu -> Ask GDB for PWD`. Does this help? 

If so, I describe how to configure this to occur automatically here: https://github.com/nakst/gf/issues/30.

> I'm also getting Python Exception <type 'exceptions.NameError'> Installation error: gdb.execute_unwinders function is missing: so maybe my setup is a bit broken.

This does appear to be a problem with your GDB/Python setup. But I believe it is unrelated to the path resolution issue.

**Comment by MrOneTwo** [comment]
That helps but stepping through code doesn't automatically update the source window.

**Comment by nakst** [comment]
Is there any information printed to stdout/stderr?

**Comment by MrOneTwo** [comment]
No, there was nothing. I have tested gf2 on a different setup (boring Ubuntu setup) while debugging M4 and it worked well. Everything points to the fact that it's my setup (Void Linux setup) that's broken. I think it would be fair to close this issue for now and we can come back to it in the future if there's actually something there.
