### ISSUE TITLE
Hardware wacthpoint is not deleted

### ISSUE THREAD

**Issue by aolo2** [nakst/gf#39]
I would expect that upon changing the watched expression or deleting it altogether the assosiated watchpoint should be deleted as well. Right now it stays on, and completely destroys the ability to restart the debugee, because something is writted to the watched address long before hitting main.

**Comment by nakst** [comment]
This behaviour is intended. In 414848d, the menu item text is made clearer to reflect this. The breakpoint window will also now display watchpoints so that they can be deleted (right click).
