### ISSUE TITLE
Arrays in the watch window have broken

### ISSUE THREAD

**Issue by aolo2** [nakst/gf#40]
Expanding any array variable in the watch window shows a python stack trace instead of the actual values:
![image](https://user-images.githubusercontent.com/17429989/127116235-b55bc63c-22a1-444d-a8be-23f51150c02c.png)

The array preview is shown just fine though:
![image](https://user-images.githubusercontent.com/17429989/127116302-f8de1c90-da2a-436c-9321-d41552241065.png)

**Comment by nakst** [comment]
Fixed in 2e6bf4c.
