### ISSUE TITLE
Alt + click doesn't seem to do anyting

### ISSUE THREAD

**Issue by aolo2** [nakst/gf#41]
While Ctrl+click outputs the `until` command as expected, clicking on a line with Alt button held down doesn't do anything.

**Comment by nakst** [comment]
Can you record a screen capture of it not working?

**Comment by aolo2** [comment]
https://user-images.githubusercontent.com/17429989/127203518-ad55c84d-a098-446a-a58e-ca0cc1f220af.mp4

**Comment by nakst** [comment]
For a frame when you click you can see a different cursor:
![image](https://user-images.githubusercontent.com/17091026/127215131-ca8b549e-d82a-4329-9796-112be604fa2b.png)
I think this means your window manager is messing something up.

As described here, https://blender.stackexchange.com/questions/24473/alt-click-is-not-selecting-edge-loops-in-linux, it might be possible to Shift+Alt+Click instead as a workaround. 

Maybe gf should allow Shift+Click as well as Alt+Click, or maybe Ctrl+RightClick? Or maybe it should be a configurable option? I'm not sure.

**Comment by aolo2** [comment]
Sharp eye! Alt + click is indeed bound to moving the whole window (which is awesome btw, and I use it all the time).Shift+Alt is unfortunately not viable for me, as it is already used to switch between keyboard layouts. Maybe a context menu for those of us who can't alt+click?

**Comment by nakst** [comment]
Added in eb05d7c.
