### ISSUE TITLE
Bitmap viewer window is too small when the bitmap is small

### ISSUE THREAD

**Issue by aolo2** [nakst/gf#43]
Viewing a 16x16 bitmap creates a tiny little window, so that the buttons, the title, and the content itself is not visible until you manually resize the window. I think the minimul allowed size for the window should be bigger.

**Comment by nakst** [comment]
Should be fixed in  2784767.

**Comment by aolo2** [comment]
Surely we have the budget to get just a few more pixels? (I'm thinking maybe 200-300)

For reference, this is how the window looks just after adding a new bitmap:
![image](https://user-images.githubusercontent.com/17429989/129396482-5ae92774-f639-4fa3-83ce-1e7b658ee094.png)

**Comment by nakst** [comment]
Added in bf25035.
