### ISSUE TITLE
How can I write a hook to display variable number of items in the watch window?

### ISSUE THREAD

**Issue by typon** [nakst/gf#50]
I am trying to write a display hook in python for a dynamic array container (for example `std::vector`).

The way I understand the hook function is that it is called twice: once to fetch the list of names of the fields, and another time to fetch their respective values.

I would like to display each item in my dynamic array as a separate element in this list of fields. I can't figure out how to change the gf code such that by the time it calls the hook with `field = None`, I already know the number of elements in my array.

Any help would be greatly appreciated.

**Comment by nakst** [comment]
I've added this in 982176e and documented it in c3aa0fb.
However I have not had a chance to test it much yet, so I'll keep this issue open for now in case there are bugs.
