### ISSUE TITLE
An optional simple workflow for loading an executable

### ISSUE THREAD

**Issue by aolo2** [nakst/gf#53]
While there are use cases for switching symbols in the middle of the debugging session, the "simple man" usage of the debugger usually invovles debugging one executable at a time with one symbol file at a time. As it stands now, the following set of commands is needed to start a debugging session at `main`:
```
file       // load the executable
set args   // set the arguments
start      // launch the executable paused so that gf can get access to the pwd
gf-get-pwd // set the pwd
start      // start debugging for real
```
While the manual control is good for some use cases, I would certainly prefer something simpler. Maybe a simple dialog to create a "run configuration", which adds the above sequence of commands to the config?

**Comment by nakst** [comment]
Added in 0cfbe2b.
