### ISSUE TITLE
gdb process crashes when using the find window

### ISSUE THREAD

**Issue by phmongeau** [nakst/gf#6]
Hi,

I've been playing with gf and I'm having a weird issue where the gdb process sometimes crashes when I use the find window.

Basic reproduction steps:

1. launch gf
2. load my program with `file` command
3.  `b main`
4.  `r`
5.  F10 a couple times
6.  open the find window with Ctrl-F, but focus back the main window without closing it
8.  gdb process crashes
9. doing an F10 or sending any other gdb command stops working

I think the crash only happens if the find window looses focus before closing, but I'm not completely sure.

I'm using a tiling window manager and the find window doesn't act as a proper popup, so it's very easy to make it loose focus.

Let me know if you need more info

[gdb_stacktrace.txt](https://github.com/nakst/gf/files/6033181/gdb_stacktrace.txt)

**Comment by nakst** [comment]
Hello, sorry I didn't see your issue earlier.

I've no idea what could be causing this issue; the find window shouldn't have any affect on GDB. You could try running gf under valgrind to see if there are any memory access problems.

That said, I removed the find dialog recently because I wasn't using it (I found it much quicker to search for what I wanted in gVim, alt-tab back to gf and press F2 to sync with gVim). Apologies :sweat_smile:

**Comment by phmongeau** [comment]
I think the issue can also happen with other windows like the theme editor.
I'll try running it under valgrind and see If there's anything suspicious

**Comment by phmongeau** [comment]
Ooooh, it has nothing to do with the find window.
The issue happens when the terminal I launched from gets resized.
The stack trace shows the crash happen in some `rl_resize_terminal` from libreadline.

```
#0  0x00007f19e07e2ef5 raise (libc.so.6 + 0x3cef5)
#1  0x00007f19e07cc862 abort (libc.so.6 + 0x26862)
#2  0x000055f9f358b4ba n/a (gdb + 0xc24ba)
#3  0x00007f19e10a1960 __restore_rt (libpthread.so.0 + 0x13960)
#4  0x00007f19e0823134 fileno_unlocked (libc.so.6 + 0x7d134)
#5  0x00007f19e1651634 rl_resize_terminal (libreadline.so.8 + 0x36634)
#6  0x000055f9f39156bd n/a (gdb + 0x44c6bd)
#7  0x000055f9f35e1c12 n/a (gdb + 0x118c12)
#8  0x000055f9f3a0accf n/a (gdb + 0x541ccf)
#9  0x000055f9f37b1806 n/a (gdb + 0x2e8806)
#10 0x000055f9f37b3d25 n/a (gdb + 0x2ead25)
#11 0x000055f9f35a2bad n/a (gdb + 0xd9bad)
#12 0x00007f19e07cdb25 __libc_start_main (libc.so.6 + 0x27b25)
#13 0x000055f9f35a992e n/a (gdb + 0xe092e)
```

If I launched gf2 and detach it from the terminal I don't get the issue
```
$ gf2 &
$ disown
```

I'm not super familiar with posix_spawn, but maybe there a flag we can pass when the gdb process is spawned to no link it to the parent terminal.

**Comment by phmongeau** [comment]
Looks like this fixes the issue

```diff --git a/gf2.cpp b/gf2.cpp
index d89cd46..04be6fa 100644
--- a/gf2.cpp
+++ b/gf2.cpp
@@ -116,7 +116,12 @@ void *DebuggerThread(void *) {
 	posix_spawn_file_actions_adddup2(&actions, inputPipe[0],  0);
 	posix_spawn_file_actions_adddup2(&actions, outputPipe[1], 1);
 	posix_spawn_file_actions_adddup2(&actions, outputPipe[1], 2);
-	posix_spawnp((pid_t *) &gdbPID, "gdb", &actions, NULL, argv, environ);
+
+	posix_spawnattr_t attrs = {};
+	posix_spawnattr_init(&attrs);
+	posix_spawnattr_setflags(&attrs, POSIX_SPAWN_SETSID);
+
+	posix_spawnp((pid_t *) &gdbPID, "gdb", &actions, &attrs, argv, environ);
 
 	pipeToGDB = inputPipe[1];
```

**Comment by nakst** [comment]
Please send a pull request of the working version.
