### ISSUE TITLE
Debugging program that uses stdin

### ISSUE THREAD

**Issue by bolt-blue** [nakst/gf#63]
Is there a reasonable way yet to debug a process that outputs to `stdout` and reads input from `stdin` - not unlike an extremely basic `ncurses`?

I've been reading this https://github.com/nakst/gf/issues/26 and the documentation on `log-window`, but it doesn't seem suitable for this use case.

**Comment by aolo2** [comment]
You could probably launch your application in a regular terminal, and then attach to it from `gf` using the PID?

**Comment by bolt-blue** [comment]
Thanks @aolo2, it sort of worked.
Definitely might be usable.
But a bit janky; not sure why. but there's a bit of a disconnect. Not sure how to describe it

**Comment by nakst** [comment]
I'm happy to take suggestions for how to improve the workflow for attaching to processes.

**Comment by bolt-blue** [comment]
@nakst Glad to hear :) I will have to experiment more and hopefully can give you some decent feedback.
And thanks for the work, it's so far the only front end to `gdb` I like using.

**Comment by nakst** [comment]
Closing this issue now. Instead, comment on issue #26 for discussing debugging programs using stdin/stdout, or create a new issue to discuss the process attach workflow.

**Comment by SanJacobs** [comment]
I'm trying to use gf to debug a program that uses `std::cin`.
If I run the program in GDB, it works just fine, aside from the fact that GDB's output and input is mixed with the program.
However, when I try to run it in gf, I get `../sysdeps/unix/sysv/linux/read.c: No such file or directory.` whenever it gets to a `std::cin`.
If I run the program normally, it's fine, but if I try to attach gf via the PID, it throws that error in gf again, and the program locks up.
