### ISSUE TITLE
feat/keybinding: goto next function and goto next function of current file

### ISSUE THREAD

**Issue by matu3ba** [nakst/gf#64]
The singlemost annoyance of gdb and lldb is that they are too stupid to understand how functions are defined or dont provide a shortcut to jump to function entry.

Functions are defined at the OS-ABI level, see [here for x86_64](https://github.com/ziglang/zig/src/arch/x86_64/abi.zig),
and it feels aweful not to abstract over them to let users jump to them on keypress.

Since this is very possible to do and is often used for tracing, ie with ftrace:
1. Is this feature feasible for this plugin? 
2. If no, how do you think this can be upstreamed to gdb/lldb?
3. What can I use instead for this functionality?

Or am I just too stupid to read the manuals properly and this is provided somewhere (at least for Linux)?

Unrelated: What do you think of a `libgdblib` to expose functions for users to write custom keyboard frontend stuff?

**Comment by nakst** [comment]
I do not understand what you mean by "shortcut to jump to function entry". Could you provide an example?

**Comment by matu3ba** [comment]
```c++
void fn1(std::string &expr) override {
... // pile of code
    if(condition)
        fn2();
}

void fn2(std::string &expr) override {
    ... // pile of code
    fn1(); // <--- debugger should stop here, since its a function entry (to inspect program state)

    ... // pile of code
    fn1(); // <--- debugger should stop here, since its a function entry (to inspect program state)
}

bool maybecallfn1_maybefn2(std::string &expr) {
    ... // some logic 
    if(stuff) // <--- debugger starts here
        fn1();
   else
        fn2(); // <---- assume fn2() is called next
    ...
}
```

I know that I can also set a breakpoint at `fn1()`, but its more effort to traverse the stack to figure out which values are in `fn2()`.
Also I dont see visually what the program did next (since I dont have a trace): I could have more indirection and need to check that first if my assumption about this being the next breakpoint is correct in the backtrace instead of having it on a simple keypress always correct.

**Comment by nakst** [comment]
If I am understanding what you are describing, then I do not know of a way that it could be implemented without it being a command added to GDB. You will have to make a feature request to the GDB or LLDB developers.
