### ISSUE TITLE
Ability to temporarily disable breakpoints

### ISSUE THREAD

**Issue by 1ndahous3** [nakst/gf#74]
https://ftp.gnu.org/old-gnu/Manuals/gdb/html_node/gdb_32.html

In some cases, this is a very useful feature available in the GUI (usually displayed as non-filled red circles as opposed to a filled circles for active ones).

**Comment by nakst** [comment]
Could you be more specific about how this feature should work in the GUI?

**Comment by s4my** [comment]
@nakst this is my proposed solution for this feature #121
