### ISSUE TITLE
Alternative to POSIX_SPAWN_SETSID?

### ISSUE THREAD

**Issue by hsnyder** [nakst/gf#76]
I'm trying to get gf2 building on FreeBSD. It actually appears to work, other than a few path changes in build.sh, but FreeBSD hasn't implemented POSIX_SPAWN_SETSID, which I understand is a nonstandard extension.

The only solution that comes to mind is to change the posix_spawnp call to a fork/setsid/exec sequence, but as I'm not deeply knowledgeable about process spawning on posix, I'd like to ask the following questions first:

- Is there an alternative to using fork/setsid/exec?
- What would be the functional consequences of simply removing `posix_spawnattr_setflags(&attrs, POSIX_SPAWN_SETSID)`?

**Comment by nakst** [comment]
I think it's used so that when gf is closed (possibly forcefully), the GDB process is automatically terminated.
As far as I am aware there should be no problem with `#ifdef`ing it away on specific platforms.

**Comment by hsnyder** [comment]
Thanks. I was having trouble with the `posix_spawn...` family of calls so I switched to fork/exec. It's now working on FreeBSD. I'll open a pull request in case you're interested in adding FreeBSD support but no pressure.
