### ISSUE TITLE
Breakpoints not cleared if filename trimmed to fit in the breakpoint window

### ISSUE THREAD

**Issue by aolo2** [nakst/gf#79]
It appears full filepaths are trimmed (to fit the "breakpoints" window maybe?). Anyway, when attempting to remove the breakpoint by right-clicking it in the "breakpoints" window and using the context menu, I get this message:
![image](https://user-images.githubusercontent.com/17429989/174829813-7e29ad09-bcce-43f4-8d34-42eab93d7a40.png)

For reference, this is how the "breakpoints" window looks:
![image](https://user-images.githubusercontent.com/17429989/174829930-2bddcc2f-65e6-4319-8e7a-c2dd1338495c.png)

**Comment by nakst** [comment]
Does it work if you bump up this constant? https://github.com/nakst/gf/blob/master/gf2.cpp#L190
