### ISSUE TITLE
Incorrect syntax highlighting for preprocessor directives

### ISSUE THREAD

**Issue by aolo2** [nakst/gf#88]
It appears all code on the same line as a preprocessor directive is highlighted using the same color. Here's a screenshot with examples of both comments and expressions getting incorrectly colored:
![image](https://user-images.githubusercontent.com/17429989/201093321-b2c7c140-433b-4dbb-848a-2504603fd0f5.png)

**Comment by s4my** [comment]
@nakst shouldn't this issue be move to the [luigi](https://github.com/nakst/luigi) repo ? a quick investigation tells me that the code responsible for this behavior is in https://github.com/nakst/gf/blob/master/luigi2.h#L2555.

**Comment by nakst** [comment]
The gf repository contains the working copy of the `luigi2.h` file. I typically only move changes over the luigi repo once they have been tested for a while in gf.

**Comment by s4my** [comment]
OK got it 👍🏻

**Comment by s4my** [comment]
@nakst this issue should be closed (fix #128), you're welcome 😎
