### ISSUE TITLE
Not compiling on 32bit linux

### ISSUE THREAD

**Issue by 9D-Tony** [nakst/gf#98]
I've trie to compile this on 32bit linux specifically Rasbperry Pi OS desktop edition
![image](https://github.com/nakst/gf/assets/3617889/5288eb2f-75e0-492b-a25e-3e416b9d86df)

Around line 5352 the count uint64_t is taken in as a unsigned long int into XGetWindowProperty(), but on 32 bit systems unsigned long int is 32 bits so gcc complains.

![image](https://github.com/nakst/gf/assets/3617889/7fb75225-4293-48d5-9a73-f16ceea19877)
 
Fixed in manually on my side by just chaning count variable to unsigned long int.

**Comment by nakst** [comment]
I think that pull request #102 fixes this. If it doesn't, please make a new issue.
